### ISSUE TITLE
`window.anonymous` usage in the wild

### ISSUE THREAD

**Issue by miketaylr** [WICG/anonymous-iframe#1]
Have y'all done any analysis of how common `window.anonymous` is on the web, maybe via HTTP Archive?

A quick search finds https://github.com/firebase/firebase-js-sdk/search?q=window.anonymous&type=code, which might create some confusing test errors down the road. Not sure that's a deal-breaker, but just flagging for awareness.

**Comment by ArthurSonzogni** [comment]
Thanks!

Initially, this was `document.anonymous`, but we realized during the implementation that this was more a property of the window instead of its documents. See: https://github.com/camillelamy/explainers/issues/21

We still expose `document.anonymous` and say it returns the document`s responsible window (if any) anonymous attribute.

I will run an HTTP archive query and put the result here once it is known. Thanks again for raising this potential issue!

**Comment by ArthurSonzogni** [comment]
Here is the public HTTP archive analysis:
https://docs.google.com/document/d/1MKGUfGzEEKpll88QspKiwDRWdkOMVh3OOXSrxGWe1Y4/edit#
Summary:
- **33** origins are serving a script containing `window.anonymous` toward **223** origins. ~80% of the subresources are coming from [https://player.gotolstoy.com/](https://player.gotolstoy.com/).
- **1** origin is serving itself a script containing `document.anonymous`.

**Comment by ArthurSonzogni** [comment]
We are going to update to a more uncommon name: `window.isAnonymousFramed`.

**Comment by mikewest** [comment]
Grammar nit: `isAnonymouslyFramed` sounds better to me. :)

**Comment by ArthurSonzogni** [comment]
Resolved in both Chrome and the specification thanks to @iVanlIsh
